# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=19)),
                ('expiry_date_month', models.CharField(max_length=2)),
                ('expiry_date_year', models.CharField(max_length=2)),
                ('card_code', models.CharField(max_length=4)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
