# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbwrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='visitor_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
