# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-22 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbwrapper', '0002_auto_20180518_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), editable=False, null=True),
        ),
    ]
